### ISSUE TITLE
No entities found, please use `entities` option

### ISSUE THREAD

**Issue by thomasraydeniscool** [mikro-orm/nestjs#10]
**Describe the bug**
When I use `forRootAsync` in the `AppModule` and define entities in their own modules using `forFeature` I get: "Error: No entities found, please use `entities` option" when I try to compile.

I read in the documentation and it says you only need define _base_ entities in `forRootAsync` so I am confused.

**Stack trace**
N/a

**To Reproduce**
1. Import `forRootAsync` in `AppModule` with no entities
2. Import `forFeature` in each module with their own entity
3. Import each module (that uses `forFeature`) in `AppModule`

**Expected behavior**
`forRootAsync` should recognize that I have entities defined using `forFeature` and therefore not require that I define any entities in `forRootAsync`.

**Additional context**
N/a

**Versions**

| Dependency | Version |
| - | - |
| node | v12.16.3 |
| typescript | v3.7.4 |
| mikro-orm | v4.2.1 (nestjs v4.2.0) |
| your-driver | mongodb |

**Comment by thomasraydeniscool** [comment]
Imported in AppModule:
```typescript
MikroOrmModule.forRootAsync({
    providers: [],
    imports: [ConfigModule.forFeature(ormConfig)],
    inject: [ConfigService],
    useFactory: (configService: ConfigService): MikroOrmModuleOptions<MongoDriver> => {
      const NODE_ENV = configService.get<string>("NODE_ENV");
      const config = configService.get<DatabaseConfig>(DatabaseConfigToken);
      return {
        type: "mongo",
        clientUrl: config.DATABASE_URI,
        highlighter: new MongoHighlighter(),
        debug: NODE_ENV === "development",
      };
    }
  })
```

UserModule:
```typescript
@Module({
  imports: [MikroOrmModule.forFeature([User])],
  controllers: [UsersController],
  providers: [UsersService],
  exports: [UsersService]
})
export class UsersModule {
}
```

**Comment by B4nan** [comment]
Nope, this is not how in works. `forFeature` is only to register repositories to nest DI, `forRoot` is for initializing the ORM and at this point it needs to know all entities.

What you can do is to uses `autoLoadEntities`, but that won't work with base entities (they need to be discovered too, but you can't register those with `forFeature` as there is no repository for them).

https://github.com/mikro-orm/nestjs#auto-entities-automatically

**Comment by thomasraydeniscool** [comment]
Thanks for clarifying @B4nan
