### ISSUE TITLE
ForceEntityConstructor can't be used with forFeature

### ISSUE THREAD

**Issue by xenoterracide** [mikro-orm/nestjs#104]
**Is your feature request related to a problem? Please describe.**

https://mikro-orm.io/docs/entity-constructors#using-native-private-properties

I don't see a good way to do this though when using `forFeature`

**Describe the solution you'd like**
A clear and concise description of what you want to happen. it should probably be just another field/array in forFeature

**Comment by B4nan** [comment]
I don't see how is that related to `forFeature`, can you be more specific?

**Comment by xenoterracide** [comment]
sorry, sure, my current understanding of `forceConstructor` is you have to either enable for everything or pass constructors.

```ts
@Global()
@Module({
  imports: [
    LoggerModule,
    CqrsModule,
    MikroOrmModule.forFeature([StorefrontProductAggregate]),
  ],
})
export class StorefrontProductModule {}
```

due to https://github.com/nestjs/cqrs/issues/1236 these aggregates would, as far as I can see (without a patch) need to use a constructor. My understanding of how to do this would be like this: however this is my global setup module. 

```ts
Global()
@Module({
  providers: [MikroListener],
  imports: [
    MikroOrmModule.forRootAsync({
      imports: [CqrsModule, MongoRepositoryLocalModule],
      inject: [MongoMemoryServer, EventPublisher],
      useFactory: (memserver: MongoMemoryServer, publisher: EventPublisher) => {
        return {
          clientUrl: memserver.getUri(),
          strict: true,
          type: 'mongo',
          validate: true,
          validateRequired: true,
          autoLoadEntities: true,
          verbose: true,
          debug: true,
          forceEntityConstructor: [StorefrontProductAggregate],
          discovery: {
            warnWhenNoEntities: false,
          },
          subscribers: [
            new EmitEventsSubscriber(),
            new EmitEventsSubscriber(),
            new AttachPublisherSubscriber(publisher),
          ],
        };
      },
    }),
  ],
})
export class MikroOrmDevConfigModule {}
```

I'm assuming this is the only way. However it would seem better to

```ts
@Global()
@Module({
  imports: [
    LoggerModule,
    CqrsModule,
    MikroOrmModule.forFeature({
          forceEntityConstructor: [StorefrontProductAggregate],
    }),
  ],
})
export class StorefrontProductModule {}
```

**Comment by B4nan** [comment]
`forFeature` is just a call to register repository inside nest DI container. you cant use it to set any configuration (other than the `entities`).

there is one hack you could use, as the `@Entity` decorator merges all of its options to the entity metadata, so you can feed it with additional stuff to put adjust the metadata of the entity. this should work too:

```ts
@Entity({ forceConstructor: true } as any)
export class StorefrontProductAggregate { ... }
```

btw do i get it right that you want to change this only for a subset of your entities? as you could just enable this globally for all the entities too

**Comment by xenoterracide** [comment]
yeah, I only want to touch the aggregate roots, not everything underneath although, I'm probably going to stick with the patch to the `cqrs` library since it doesn't involve making everything ugly using `!` or `?`. Sorry that it appears this one was actually a question. Although perhaps the docs could be improved (I always personally prefer questions to be answered with more docs ;) )
