### ISSUE TITLE
reflect MultiRequestContext for nestjs

### ISSUE THREAD

**Issue by muradm** [mikro-orm/nestjs#11]
There is a fresh [enhancement-872](https://github.com/mikro-orm/mikro-orm/issues/872) which adds `MultiRequestContext`. Do you have a plan to reflect its impact for nestjs? I.e. how multiple instances could be used under nestjs?

**Comment by B4nan** [comment]
It should be possible to use it right now, by disabling the automatic context middleware (`registerRequestContext: false`) and creating your own, where you use the `MultiRequestContext` instead.

**Comment by B4nan** [comment]
Closing as duplicate of #20, let's track this there.
