### ISSUE TITLE
Add Nest.js v10 in peer dependencies

### ISSUE THREAD

**Issue by michael-zbooni** [mikro-orm/nestjs#122]
**Is your feature request related to a problem? Please describe.**
Nest.js v10 has been released, but the peer dependencies are:

```
"@nestjs/common": "^8.0.0 || ^9.0.0",
"@nestjs/core": "^8.0.0 || ^9.0.0"
```

**Describe the solution you'd like**
Perhaps another `|| ^10.0.0`?  Nest.js changelog said that:

> There were some very minor breaking changes that shouldn't affect most users - you can find the full list of them [here](https://github.com/nestjs/nest/releases/tag/v10.0.0).

**Describe alternatives you've considered**
none

**Additional context**
It doesn't seem urgent, but it could be a blocker for new Nest.js projects or those who want to update to Nest.js v10.

**Comment by B4nan** [comment]
PR welcome

**Comment by jasonnoble** [comment]
@michael-zbooni @B4nan It looks like @renovate-bot tried via #120. According to [this](https://trilon.io/blog/nestjs-10-is-now-available#dropping-support-for-nodejs-v12) Node v16 is now required.

I created #124 that has @renovate-bot 's changes as well as changing the build to v16 only.

**Comment by B4nan** [comment]
Well, that's a breaking change, so that would have to wait for v6, and I won't be releasing that before the ORM v6 is ready. I would only alter the peer dependency ranges to allow it for v5.

**Comment by jasonnoble** [comment]
@B4nan https://github.com/mikro-orm/nestjs/pull/124/files Are the dev dependencies ok to lock to nest v10?

**Comment by B4nan** [comment]
Kinda, but it would require the CI to run only on node 16, and I'd rather not do that now. Once v6 is out, I will ship v6 of this package too, which will require node 16 (or maybe even node 18, as v16 will reach EOL later this year too).

So for now let's just alter the peer dependencies.

**Comment by wavedeck** [comment]
I‘d appreciate an update of the peer dependencies as I’m currently preparing to migrate from nestjs v9 to v10. The biggest selling point for me is finally ESM support as a lot of my preferred packages are switching to or are already ESM-only.

It‘s a pain in v9 as i‘d either have to use alternative packages (more bloated, slower, less feature rich…) Nestjs v10 solves this by setting it‘s target to ES2021 which works a lot nicer with ESM than the previous version.

Looking forward to see updated peers for @micro-orm/nestjs
