### ISSUE TITLE
[Question] Using AsyncLocalStorage

### ISSUE THREAD

**Issue by ardyfeb** [mikro-orm/nestjs#13]
I currently going to refactor previous orm on our nestjs backend from Typeorm to Mikro ORM, i see using Mikro ORM with nestjs requiring RequestContext Middleware to ensure each request have clean entity manager state. Because middleware is only for regular http request and cannot be used on background job, queue, or any task running on background.

So using entity manager outside request scope the function should be anotated with `@UseRequestContext` (i aware with this because we have large codebase that mostly run on background will cause DRY Code)

If using `AsyncLocalStorage` instead `RequestContext` still we need anotate the function with `UseRequestContext` ? i look into `UseRequestContext` there no conditional case if context handled by request or local storage

**Comment by B4nan** [comment]
`@UseRequestContext` decorator is currently bound to the domain api only, but the code is very simple, you can create custom decorator that will use the ALS easily.

https://github.com/mikro-orm/nestjs/blob/master/src/mikro-orm.common.ts

**Comment by ardyfeb** [comment]
So `@UseRequestContext` not need when using `AsyncLocalStorage` ? but how to achieve same behavior with `AsyncLocalStorage` ? or its not required ?

**Comment by marcus-sa** [comment]
I'm curious about this as well, since I'm trying to use ALS for event based request contexts.

**Comment by B4nan** [comment]
v5 is using ALS by default
