### ISSUE TITLE
MetadataError: Duplicate entity names are not allowed: "User"

### ISSUE THREAD

**Issue by thiagomini** [mikro-orm/nestjs#132]
**Describe the bug**

* **Given** we are using Entity Schema definitions
* **And** we have a `User` entity class with its schema
* **And** we're using the `autoLoadEntitites: true` option.
* **When** we execute two subsequent test files that import the `MikroORMModule`
* **Then** we got an error: `MetadataError: Duplicate entity names are not allowed: User`

**Stack trace**
```
 FAIL  src/mikro-orm/another-module-using-mikro-orm.spec.ts > MikroOrmInternalModule > connects to the database
MetadataError: Duplicate entity names are not allowed: User
 ❯ Function.duplicateEntityDiscovered node_modules/@mikro-orm/core/errors.js:172:16
 ❯ MetadataValidator.validateDiscovered node_modules/@mikro-orm/core/metadata/MetadataValidator.js:53:42
 ❯ MetadataDiscovery.findEntities node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:94:24
 ❯ MetadataDiscovery.discover node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:34:9
 ❯ MikroORM.discoverEntities node_modules/@mikro-orm/core/MikroORM.js:119:25
 ❯ Function.init node_modules/@mikro-orm/core/MikroORM.js:34:9
 ❯ TestingInjector.instantiateClass node_modules/@nestjs/core/injector/injector.js:369:37
 ❯ callback node_modules/@nestjs/core/injector/injector.js:65:34
 ❯ TestingInjector.resolveConstructorParams node_modules/@nestjs/core/injector/injector.js:144:24
 ❯ TestingInjector.loadInstance node_modules/@nestjs/core/injector/injector.js:70:13

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { entity: undefined, getEntity: 'Function<getEntity>' }
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

**To Reproduce**
1. Clone the minimum reproducible code repository: https://github.com/thiagomini/nest-mikro-orm-example/tree/bug/vitest-and-another-module
2. run `yarn`
3. run `docker compose up -d`
4. run `yarn test --threads=false`

**Expected behavior**
The tests should pass

**Additional context**
There is a specific set of configurations that make setup fail, which is using vitest and `threads=false`. I'm not sure how to tackle this, but I understand what's happening under the hood:

1. `MetadataStorage` class has a static property for entities
2. When the first test file runs, it registers all entities
3. When the second test file runs, it keeps the first entity, and it finds the same entity again, which throws an error

Would it be possible to provide an option for Mikro-orm to ignore duplicates? That would already make it work for me. Another option would be to provide some functionality to **rediscover** entities and **clear** the `EntityStorage` programmatically, which I'd do in the `beforeEach` and `afterEach` hooks.

**Versions**
| Dependency | Version |
| - | - |
| node | 18.12.1 |
| typescript | 5.1.3 |
| mikro-orm | 5.7.14 |
| pg | 8.11.2 |

**Comment by thiagomini** [comment]
By the way, I could open a PR for that if Martin points me to where this could be done. Thanks!

**Comment by B4nan** [comment]
This sounds weird, the static register is always populated first as the decorators are evaluated on import time, before the `MikroORM.init` call, so it shouldn't really matter.

The validation there is pretty important, you need to have the same prototype discovered as the one you will be using in your code. So just disabling it seems like it won't help much, you'd really have to replace things if something. Does it actually help you locally when you just comment out the validation? If the classes are identical (`User === User`) we could just deduplicate that automatically, the validation is there because of using different class references or different classes with the same name.

**Comment by thiagomini** [comment]
Hey, @B4nan , thanks for the response! 

> This sounds weird, the static register is always populated first as the decorators are evaluated on import time, before the MikroORM.init call, so it shouldn't really matter.

I agree, it should have been called only once, Idk why this is happening to be honest.

> Does it actually help you locally when you just comment out the validation?

Yes, the tests pass if I comment out both validations (For tableName and Duplicates). So, I believe [this feature PR](https://github.com/mikro-orm/mikro-orm/pull/4618) could solve my issue here.

What are your thoughts on that?

**Comment by B4nan** [comment]
What if you change [that line](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/metadata/MetadataValidator.ts#L61) to:

```diff
-const duplicates = Utils.findDuplicates(discovered.map(meta => meta.className));
+const duplicates = Utils.findDuplicates(discovered.map(meta => meta.class));
```

**Comment by thiagomini** [comment]
Hey again, @B4nan , this is the output I got:

`Set(2) { [class User], [class User] }`

So, I believe they are not unique

**Comment by thiagomini** [comment]
Hey @B4nan, I apologize for bothering you with this again, but do you have any plans on when you'll release the next version of Mikro-orm? Just so we can update it in the corresponding Nest Package - I'm looking forward to using Mikro-orm in our application, and this is the last blocker for us.

**Comment by B4nan** [comment]
You can use the dev version, every commit to master is published to NPM.
