### ISSUE TITLE
Error when trying to query an entity from the repository

### ISSUE THREAD

**Issue by thiagomini** [mikro-orm/nestjs#135]
**Describe the bug**
* **Given** we are using Entity Schema definitions
* **And** we have an `Address` entity class and schema
* **And** we have a `User` entity class that has many addresses (`1:m` relation)
* **And** we're using the `autoLoadEntitites: true` option.
* **When** we try to fetch an existing user from the repository: `await repository.findOneOrFail(user.id)`
* **Then** we got an error: Trying to query by not existing property Address.undefined`

**Stack trace**
```
 FAIL  src/mikro-orm/mikro-orm-internal.module.spec.ts > MikroOrmInternalModule > finds an existing user
Error: Trying to query by not existing property Address.undefined
 ❯ node_modules/@mikro-orm/knex/query/CriteriaNode.js:28:27
 ❯ new CriteriaNode node_modules/@mikro-orm/knex/query/CriteriaNode.js:23:17
 ❯ new ScalarCriteriaNode node_modules/@mikro-orm/knex/query/ScalarCriteriaNode.js:9:1
 ❯ Function.createScalarNode node_modules/@mikro-orm/knex/query/CriteriaNodeFactory.js:25:22
 ❯ Function.createNode node_modules/@mikro-orm/knex/query/CriteriaNodeFactory.js:22:21
 ❯ Function.createObjectItemNode node_modules/@mikro-orm/knex/query/CriteriaNodeFactory.js:51:25
 ❯ node_modules/@mikro-orm/knex/query/CriteriaNodeFactory.js:42:28
 ❯ Function.createObjectNode node_modules/@mikro-orm/knex/query/CriteriaNodeFactory.js:41:45
 ```

**To Reproduce**
1. Clone the minimum reproducible code repository: https://github.com/thiagomini/nest-mikro-orm-example/tree/bug/trying-to-query-by-non-existing-property
2. run `yarn`
3. run `docker compose up -d --build`
4. run `yarn test`

**Expected behavior**
The tests should pass

**Additional context**
I would like to know if by default an entity eagerly loads its relationships. I'm asking this because I had to load them in the [test case](https://github.com/thiagomini/nest-mikro-orm-example/blob/935b2d234788d2befc992d89a0ed3d08f071f0d1/src/mikro-orm/mikro-orm-internal.module.spec.ts#L46) forcefully with `await foundUser.addresses.init();`.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.12.1 |
| typescript | 5.1.3 |
| mikro-orm | 5.7.14 |
| pg | 8.11.2 |

**Comment by B4nan** [comment]
You are missing the M:1 owning property in Address entity. You cannot have a 1:M relation without it.

https://github.com/thiagomini/nest-mikro-orm-example/blob/bug/trying-to-query-by-non-existing-property/src/mikro-orm/address.schema.ts#L14-L16

**Comment by thiagomini** [comment]
Hey Martin, I have added the inverse side of the operation in the [address schema](https://github.com/thiagomini/nest-mikro-orm-example/blob/61b24b32e3748e93acc632b0b1f7b8ebc02014e3/src/mikro-orm/address.schema.ts), but it still throws a weird error:

```
SyntaxErrorException: insert into "address" ("user_id", "street") values ('10', '10', 'street') returning "id" - INSERT has more expressions than target columns
 ❯ PostgreSqlExceptionConverter.convertException node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:32:24
 ❯ PostgreSqlDriver.convertException node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:197:54
 ❯ node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:201:24
 ❯ PostgreSqlDriver.nativeInsertMany node_modules/@mikro-orm/knex/AbstractSqlDriver.js:303:21
 ❯ ChangeSetPersister.persistNewEntity node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:85:21
 ❯ ChangeSetPersister.executeInserts node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:29:13
 ❯ ChangeSetPersister.runForEachSchema node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:13
 ❯ UnitOfWork.commitCreateChangeSets node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:739:9
 ❯ UnitOfWork.persistToDatabase node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:703:13
 ❯ Parser.parseErrorMessage node_modules/pg-protocol/src/parser.ts:369:69
 ❯ Parser.handlePacket node_modules/pg-protocol/src/parser.ts:188:21
 ❯ Parser.parse node_modules/pg-protocol/src/parser.ts:103:30
 ❯ Socket.<anonymous> node_modules/pg-protocol/src/index.ts:7:48
 ❯ Socket.emit node:events:513:28
 ``` 
 
 Can you help me pointing what I'm doing wrong here?

**Comment by B4nan** [comment]
You cannot map single column to multiple properties, so yes, you need to replace the `userId`, not add a new relation property and keep it.
