### ISSUE TITLE
Bump version, compatible with MikroORM V6

### ISSUE THREAD

**Issue by darky** [mikro-orm/nestjs#155]

**Comment by B4nan** [comment]
Current version is already compatible.

**Comment by darky** [comment]
Not exactly
Peer dependency error
https://github.com/mikro-orm/nestjs/blob/master/package.json#L43

**Comment by B4nan** [comment]
I dont see any peer dependency error (https://github.com/mikro-orm/nestjs-realworld-example-app), `^6.0.0-dev` already supports any 6.0 stable version.

<img width="478" alt="image" src="https://github.com/mikro-orm/nestjs/assets/615580/e471bf4e-0c58-4219-bb07-8f69b7f93cee">
<img width="208" alt="image" src="https://github.com/mikro-orm/nestjs/assets/615580/021f2fce-ddde-47e8-a1a1-7669992b8d14">

**Comment by darky** [comment]
Maybe this calculator don't work perfectly, I have error during `npm install`
Anyway I create PR https://github.com/mikro-orm/nestjs/pull/156

**Comment by B4nan** [comment]
as i said, i dont see any errors, tried with npm and yarn in the realworld example app, no issues there

anyway, i will ship v6 of this package too later this week (maybe even today). if you see issues with peer deps, you can always just use `--force` to get around them.

**Comment by darky** [comment]
> you can always just use --force to get around them

Already

**Comment by Sundhar-Karunanidi-Bjss** [comment]
Is there a way to pre build a cache when dynamically creating a config using the forrootasync function?
