### ISSUE TITLE
Custom decorators using class validator 

### ISSUE THREAD

**Issue by Lishenga** [mikro-orm/nestjs#16]
Does MikroORM allow the querying of entities inside a custom decorator using class validator. For instance like this

<img width="868" alt="Screenshot 2021-01-30 at 13 20 12" src="https://user-images.githubusercontent.com/33782195/106353764-fd3fd900-62fd-11eb-848c-dac90c6a9541.png">

When i execute the above code out, i get an error "Cannot read property 'findOne' of undefined"
So am wondering if MikroORM does support querying of entities inside custom decorator using class validator.
The code that executes the custom decorator is this 

<img width="758" alt="Screenshot 2021-01-30 at 13 23 46" src="https://user-images.githubusercontent.com/33782195/106353834-763f3080-62fe-11eb-99da-b5e1a7873292.png">

I will highly appreciate your assistance

**Comment by B4nan** [comment]
Well, this is not about MikroORM support, this does not make sense in general. What is `this` inside that context? How would he repository instance get inside that context? That is the error you are seeing - you try to execute a method on repository that is not there.

**Comment by Lishenga** [comment]
Thank you so much, any idea how i would make database queries in that context?

**Comment by TLmaK0** [comment]
Take a look to https://github.com/nestjs/nest/issues/528
