### ISSUE TITLE
vitest + mikroorm collection error

### ISSUE THREAD

**Issue by philWeroad** [mikro-orm/nestjs#160]
Hi @B4nan! We are facing a problem, regarding collections, switching from `jest` to `vitest` in a nestjs (with mikroorm) project.

When we `set` an entity collection inside its constructor
```js
constructor(properties: ICreateAuthor) {
    Object.assign(this, {
      name: properties.name,
      email: properties.email,
      active: properties.active,
      bio: properties.bio,
    });

    this.books.set(properties.books);
 }
```
we faced the following error: `TypeError: Cannot read properties of undefined (reading '__meta')`.

**Stack trace**
```
 ❯ Collection.get property [as property] node_modules/@mikro-orm/core/entity/ArrayCollection.js:269:56
 ❯ Collection.validateItemType node_modules/@mikro-orm/core/entity/Collection.js:377:71
 ❯ node_modules/@mikro-orm/core/entity/Collection.js:104:42
 ❯ Collection.add node_modules/@mikro-orm/core/entity/Collection.js:104:19
 ❯ Collection.set node_modules/@mikro-orm/core/entity/ArrayCollection.js:70:14
 ❯ Collection.set node_modules/@mikro-orm/core/entity/Collection.js:113:15
 ❯ new AuthorEntity src/modules/author/entities/author.entity.ts:44:16
     42|     });
     43| 
     44|     this.books.set(properties.books);
       |                ^
     45|   }
     46| 
 ❯ Function.create src/modules/author/entities/author.entity.ts:48:12
 ❯ AuthorDomainService.createAuthor src/modules/author/author.service.ts:12:36
```
** Versions **
- "@mikro-orm/core": "5.9.7"
- "@mikro-orm/nestjs": "5.2.3"
- "@mikro-orm/postgresql": "5.9.7"
- "@nestjs/common": "^10.0.0"
- "@nestjs/core": "^10.0.0"

PS: you can find all versions in the github repo

**To Reproduce**
I prepared a repo to reproduce the problem: https://github.com/philWeroad/nestjs-vitest.
You can follow the readme to install all the required dependencies and to run the unit tests.
It requires `docker` and `docker compose`

**Expected behavior**
Unit test with vitest works fine as with jest.

Any advice?
Thanks

**Comment by B4nan** [comment]
Looking at the stack trace, this almost certainly means the entity is not a discovered class prototype.

Since you are using folder-based discovery and vitest, maybe you need to use the `dynamicImportProvider` option as described in the [getting started guide](https://mikro-orm.io/docs/guide/project-setup#testing-the-endpoint):

```ts
dynamicImportProvider: id => import(id),
```

**Comment by philWeroad** [comment]
Hi @B4nan, thanks for your reply.
I followed your suggestions, but unfortunately the same error remains. It's clear that it is a problem of loading the relations of an entity, but honestly, I can't figure it out.
The sample project is updated with your suggestions, can I ask you to open it and try to go deeper?

**Comment by B4nan** [comment]
> It's clear that it is a problem of loading the relations of an entity

It's not about loading relations (data), it's about entity discovery (using wrong class prototypes, not the discovered ones). That's the reason why the metadata are not properly set on the class prototypes, which in turn results in that error.

I will have a closer look.

**Comment by B4nan** [comment]
Tried to upgrade that repro to v6 and looks like that resolves it on its own, so closing. If it wouldn't help, please update the repro to use v6 and let me know here.
