### ISSUE TITLE
autoLoadEntities does not work when using Test.createTestingModule

### ISSUE THREAD

**Issue by roderik** [mikro-orm/nestjs#17]
**Describe the bug**

I recently switched to the `autoLoadEntities` way to load entities.

Imagine the following "flow"

- MainAppModule
  - imports AuthModule
    - imports UserModule
      - imports MikroOrmModule.forFeature([User])

This works perfectly while running the application.

But when testing this, the entities do not get loaded.   

```
  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [MainAppModule],
    }).compile();
```

Gives me the following stack trace

```
    No entities found, please use `entities` option

      at Configuration.validateOptions (../../node_modules/@mikro-orm/core/utils/Configuration.js:146:19)
      at new Configuration (../../node_modules/@mikro-orm/core/utils/Configuration.js:22:18)
      at new MikroORM (../../node_modules/@mikro-orm/core/MikroORM.js:20:27)
      at Function.init (../../node_modules/@mikro-orm/core/MikroORM.js:38:21)
      at InstanceWrapper.useFactory [as metatype] (../../node_modules/@mikro-orm/nestjs/mikro-orm.providers.js:21:32)
      at Injector.instantiateClass (../../node_modules/@nestjs/core/injector/injector.js:289:55)
      at callback (../../node_modules/@nestjs/core/injector/injector.js:42:41)
      at Injector.resolveConstructorParams (../../node_modules/@nestjs/core/injector/injector.js:114:24)
      at Injector.loadInstance (../../node_modules/@nestjs/core/injector/injector.js:46:9)
```

I can work around it by putting a MikroOrmModule.forFeature for all entities referenced when initializing the testing module but this is less than optimal.

**Versions**

| Dependency | Version |
| - | - |
| node | v14.15.1 |
| typescript | 4.1.3 |
| mikro-orm | 4.4.0 |
| mongo | 3.6.3 |

**Comment by anlauren** [comment]
Hello! any news on that? from what i'm reading in the module code it would be because this line:
```js
 const key = (preferTsNode && this.config.get('tsNode', Utils_1.Utils.detectTsNode()) && this.config.get('entitiesTs').length > 0) ? 'entitiesTs' : 'entities';
```
returns "entities" instead of "entitiesTs". Would it come from the fact that jest config says `ts-jest`
I'm not sure if there's a way around to enforce ts node in a test config, i see the `preferTsNode` value there 🤔

**Comment by B4nan** [comment]
You can control that just by passing `tsNode: true` to the ORM config - that way the detection is skipped and `entitiesTs` will be used.

**Comment by anlauren** [comment]
Beautiful i'll try this out!

**Comment by anlauren** [comment]
Works nicely!
Don't know if it's worth mentioning somewhere in the docs for people using jest in that way 🤔

**Comment by B4nan** [comment]
ts-jest detection will land soon hopefully, related PR adding support for detecting ts-jest: https://github.com/kulshekhar/ts-jest/pull/2717

**Comment by B4nan** [comment]
Closing, should work out of box with ts-jest 27.0.4+ and MikroORM v4.5.9+

**Comment by xenoterracide** [comment]
tried ts-node: true in the latest, though I'm not actually certain that's what we're doing. didn't work, same problem. Feels like a hokey fix though.

**Comment by xenoterracide** [comment]
note: I think we might be using babel...

**Comment by xenoterracide** [comment]
```
❯ yarn why ts-jest
└─ services-core@workspace:.
   └─ ts-jest@npm:27.1.5 [8316d] (via npm:27.1.5 [8316d])
❯ yarn why @mikro-orm/core
└─ services-core@workspace:.
   └─ @mikro-orm/core@npm:5.6.3 [8316d] (via npm:^5.6.3 [8316d])
❯ yarn why jest
├─ jest-cucumber@npm:2.0.12
│  └─ jest@npm:27.5.1 [8875a] (via npm:27.5.1 [8875a])
│
└─ services-core@workspace:.
   └─ jest@npm:27.5.1 [8875a] (via npm:27.5.1 [8875a])
```
