### ISSUE TITLE
Error when using ResolveField of graphql and populate of mikro-orm

### ISSUE THREAD

**Issue by oqlioc** [mikro-orm/nestjs#18]
**Describe the bug**
If mikro-orm populate in community <- board <- post relationship,
board Collection object, ResolveField continues to run and an error appears.
I want to use both. Is there a solution?

Entitiy
```
@ObjectType('Community')
@Entity({ tableName: 'community.community'})
export class Community {

  @Field(() => ID)
  @PrimaryKey({ type: BigIntType })
  id?: string;
}
```

```
@Entity({ tableName: 'community.board' })
@ObjectType('Board')
export class Board {
  @PrimaryKey({ type: BigIntType})
  @Field(() => ID)
  id: string;

  @ManyToOne(() => Community, { fieldName: 'community_id'})
  community: Community;

  @OneToMany(() => Post, (post) => post.board, { orphanRemoval: true })
  post? = new Collection<Post>(this);

  @Field({ defaultValue: 0 })
  postCnt?: number;
}
```

```
@Entity({ tableName: 'community.post' })
@ObjectType('Post')
export class Post {
  @PrimaryKey({ type: BigIntType })
  @Field(() => ID)
  id: string;

  @ManyToOne(() => Board, { fieldName: 'board_id'})
  board: Board;
}

```
Resolver
```
@Resolver(() => Board)
@UseGuards(SessionGuard)
export class BoardResolver {
  constructor(private readonly em: EntityManager) {}

  @Query(() => [Board], { nullable: true })
  async getBoardList(@Args('communityId') communityId: number): Promise<Board[]> {
    return await this.em.find(Board, { community: { id: String(communityId) } }, ['post']);
  }

  @ResolveField(() => Int, { name: 'postCnt' })
  async getPostCnt(@Parent() board: Board) {
    return await this.em.count(Post, { board: board.id });
  }
}
```

**Error message**

console
```
[NestWinston] Error     2021. 3. 3. 오후 1:43:09 /graphQL Maximum call stack size exceeded undefined INTERNAL_SERVER_ERROR - {}
```

graphql error message
```
{
  "errors": [
    {
      "message": "Maximum call stack size exceeded"
    }
  ],
  "data": {
    "getBoardList": null
  }
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | v14.15.4 |
| typescript | 4.1.3 |
| mikro-orm | 4.4.3 |
| postgresql | ? |

**Comment by B4nan** [comment]
Would be good to spend more time on debugging, I don't think there will be anybody able to help with this without seeing at least the full stack trace. I don't see anything that would point to issue in MikroORM from what you posted. Not talking about this being probably a GQL issue, not connected to the ORM.

Also I don't really understand the point of using big ints and mapping them to JS numbers - you will loose precision. One more note - you don't need that `{ id: ... }` in your queries, it is fine (or even preferrrable) to use the ID right ahead:

```ts
// and again, the type casting to number and string makes not sense
return await this.em.find(Board, { community: String(communityId) }, ['post']);
```

Also check out this project: https://github.com/driescroons/graphql-fields-to-relations

I will close this as it it is not actionable. If you want to file a bug report, please do so without using GQL and provide something reproducible. Or open it elsewhere - somewhere where GQL is actually a part of the product, so you can get some GQL help - can't help with that, this project is not related to (or is using) GQL anyhow, neither am I.
