### ISSUE TITLE
Move into the mikro-orm repo

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/nestjs#19]
The MikroORM repo contains a lot of different packages: cli, db-adapters, knex, core, migrations. It seems weird that the nestjs package is not in this repo. 
There are also a few advantages to mergen this into the main repo. It would keep the version at the same level as the main MikroORM package, keeps dependencies up to date and with that shows users that this package is serious and begin kept up to date and it looked after.

**Comment by B4nan** [comment]
I want to keep it outside, there is no need to sync the version, I see it the opposite way - version bump here has a meaning, there is a change in this package (if we had it in the main one, there would be new versions and pretty much no changes). 

I do sync the major versions as those usually require some updates, but I don't see any benefits doing the sync for minor and patch versions. 

Also, this package has no direct dependencies, only peers and dev deps. I don't see anything wrong or outdated here, the version of nest or the orm in tests is quite irrelevant (only the major version is). We can set up renovate here as well, if that bothers you (it will be much less time than migrating this into the monorepo anyway).

**Comment by Langstra** [comment]
That is a valid point, but that would be the same for all the other packages in the MikroORM repo. Even though they are probably more often updated than this one, they still get a version bump, even when they have have no changes. 

I think it would not hurt to keep the dependencies up to date, maybe something seemingly irrelevant breaks the package and in such case we'd like to know.

**Comment by B4nan** [comment]
> That is a valid point, but that would be the same for all the other packages in the MikroORM repo. Even though they are probably more often updated than this one, they still get a version bump, even when they have have no changes.

For me its quite different with the packages from monorepo. They form the ORM and are much more tighly coupled. Developing something in one package often involves changes in others. 

On the other hand, this is an adapter that ingerating two libraries together and is more of an extension for nest than MikroORM - that is maybe the biggest reason why I dislike it being there.
