### ISSUE TITLE
Multiple database connections

### ISSUE THREAD

**Issue by AaronPerezPerez** [mikro-orm/nestjs#20]
We currently have two MikroORM instances, one connecting to a MongoDB and another connecting to a PostgreSQL, but we are facing troubles as the configs are being confused.

We implemented it like this.

This is the module that allows us to  choose if we want to use real or fake repositories on the tests suites
```typescript
@Module({})
export class MikroOrmSwitcherModule {
  static init({ disable }: { disable: boolean }): DynamicModule {
    if (disable) {
      return {
        module: MikroOrmSwitcherModule,
      };
    }

    return {
      module: MikroOrmSwitcherModule,
      imports: [
        MikroOrmModule.forRoot(mikroOrmPostgresConfig),
        MikroOrmModule.forRoot(mikroOrmMongoConfig),
      ],
    };
  }
}
```
This is the `mikro-orm-mongo.config.ts`:
```typescript
const mikroOrmMongoConfig: Options = {
  type: 'mongo',
  contextName: 'mongoConfig',
  name: 'mongoDB',
  host: config.transactionsDatabase.host,
  port: config.transactionsDatabase.port,
  user: config.transactionsDatabase.username,
  password: config.transactionsDatabase.password,
  dbName: config.transactionsDatabase.database,
  entities: [CustomerOrderEntity, CancelationEntity, OrderLineEntity, LocationEntity],
  debug: true,
  metadataProvider: TsMorphMetadataProvider,
};

export default mikroOrmMongoConfig;
```
This is the `mikro-orm-postgres.config.ts`:
```typescript
const mikroOrmPostgresConfig: Options = {
  type: 'postgresql',
  contextName: 'postgreSQLConfig',
  name: 'postgreSQL',
  host: config.ledgersDatabase.host,
  port: config.ledgersDatabase.port,
  user: config.ledgersDatabase.username,
  password: config.ledgersDatabase.password,
  dbName: config.ledgersDatabase.database,
  entities: [LedgerEntity],
  migrations: {
    path: 'src/migrations',
  },
  debug: true,
  metadataProvider: TsMorphMetadataProvider,
};

export default mikroOrmPostgresConfig;
```
The failures we are getting are that sometimes our orm instances trys to use the  PostgreSQL driver for the MongoDB repository and sometimes the opposite.

At the config files we tried to add only the entities that each instance is going to use, but that gives us the following error also:
`[Nest] 24318   - 25/03/2021 11:17:27   [ExceptionHandler] Metadata for entity CustomerOrderEntity not found +0ms`

We haven't found a proper way to achieve this in the documentation. Thanks in advance!

**Comment by B4nan** [comment]
This will be caused by how the nest adapter registers the EM and repositories - both of your ORM instances will use the same tokens in the DI.  You should be able to register things yourself manually.

Also you will need to handle the request context manually and give your ORM instances distinct names. See the tests:

https://github.com/mikro-orm/mikro-orm/blob/master/tests/RequestContext.test.ts#L64

**Comment by AaronPerezPerez** [comment]
Hi again, what we finally did was to provide two different MikroORM instances instead of using the `MikroOrmModule.forRoot()` and then inject them in our repositories.
It looks like this:
```typescript
@Global()
@Module({})
export class MikroOrmSwitcherModule {
  static init({ disable }: { disable: boolean }): DynamicModule {
    if (disable) {
      return {
        module: MikroOrmSwitcherModule,
      };
    }

    return {
      module: MikroOrmSwitcherModule,
      providers: [
        {
          provide: MIKRO_ORM_MONGODB_TOKEN,
          useValue: MikroORM.init(mikroOrmMongoConfig),
        },
        {
          provide: MIKRO_ORM_POSTGRESQL_TOKEN,
          useValue: MikroORM.init(mikroOrmPostgresConfig),
        },
      ],
      exports: [MIKRO_ORM_MONGODB_TOKEN, MIKRO_ORM_POSTGRESQL_TOKEN],
    };
  }
}```

And this is the repository contructor:
```typescript

  constructor(
    @Inject(MIKRO_ORM_POSTGRESQL_TOKEN) private readonly orm: MikroORM<PostgreSqlDriver>,
  ) {
    this.ledgerRepository = this.orm.em.getRepository(LedgerEntity);
  }```

We thought that this may be useful for you, so we wanted to share it!

**Comment by B4nan** [comment]
You still need to register the request context yourself, as it was done automatically for you via `MikroOrmModule.forRoot()` that is no longer used.

Each request needs to have its own context, using global one will cause side effects and memory leaks.

https://mikro-orm.io/docs/identity-map/#why-is-request-context-needed

**Comment by jasonwilson** [comment]
@B4nan thanks for referencing this issue was able to setup a similar environment splitting out each database as a separate orm instance. 

We rely in the mikro-orm tooling which looks for `mikro-orm.config.ts`.  Is there a a way to dynamically specify the configuration or connection in the cli? If not might be something to consider for v5.

**Comment by B4nan** [comment]
You could override any config option via env vars.

https://mikro-orm.io/docs/configuration/#using-environment-variables

**Comment by jasonwilson** [comment]
This would work as a "one off" for running commands but there's no way to inject or share `.env` configuration into the app when using multiple connections. 

Another option would be to specify the `mikro-orm.config.ts` path via environment variable. I didn't see that option in the list, let me know if I missed it.

**Comment by B4nan** [comment]
Nope, that's not possible.

You can either wait for #545 or of course you could send a PR right ahead :] 

If nobody contributes, will probably do it before v5 is out myself.

**Comment by jasonwilson** [comment]
I'm happy to open a PR for specifying orm config via env variable if you'll accept it.

**Comment by B4nan** [comment]
Sure we can start with that, I'd also add a CLI option for this ideally. 

Just keep in mind that master is already v5 and I am not planning to backport features to v4, so if you will want to benefit from that, you will need to switch to v5 dev version.

**Comment by B4nan** [comment]
Or actually this is already implemented, almost forgot about that - you can use `MIKRO_ORM_CLI` env var which will add the CLI config path.

> You can also use different names for this file, simply rename it in the `configPaths` array your in `package.json`. You can also use `MIKRO_ORM_CLI` environment variable with the path to override `configPaths` value.

https://mikro-orm.io/docs/installation/#setting-up-the-commandline-tool

**Comment by EduVencovsky** [comment]
I'm still lost on how to connect to multiple databases (In my case, I want to connect to two different postgres databases).

Is there any way to do this without any problems or it still needs a PR?

**Comment by gianlazz** [comment]
I also have this as a required use case in the process of migrating from typeorm on an existing project where I had two databases supported. Using `MIKRO_ORM_CLI` appears to be working for me 🎉 

For example, I have a `mikro-orm.sqlite.config.js` & `mikro-orm.postgres.config.js` file respectively for each. Then use commands as such:

```bash
$ MIKRO_ORM_CLI=$PWD/mikro-orm.sqlite.config.js mikro-orm debug
# or
$ MIKRO_ORM_CLI=$PWD/mikro-orm.postgres.config.js mikro-orm debug
```

**Comment by tsangste** [comment]
I tried my hand at implementing multiple database connections as this is something that would benefit us

**Comment by B4nan** [comment]
For reference, v6 also adds a `--config` CLI option:

https://github.com/mikro-orm/mikro-orm/pull/3924
