### ISSUE TITLE
The UseRequestContext make the method return void

### ISSUE THREAD

**Issue by hong-duc** [mikro-orm/nestjs#21]
**Describe the bug**
I am develop chat app with nestjs gateway(socketio). I apply UseRequestContext on a method in the service that have it return a value, but it return void instead. When I remove UseRequestContext it return value normal

**To Reproduce**
1. Write a Service with method return value
2. Apply UseRequestContext to method
3. Call it

**Expected behavior**
Method return value

**Versions**
"@mikro-orm/core": "^4.3.4",
"@mikro-orm/nestjs": "^4.2.0",

| Dependency | Version |
| - | - |
| node | 10.19.0 |
| typescript | ^3.7.4 |
| mikro-orm | ^4.3.4 |
| postgres | ^4.3.4 |

**Comment by Langstra** [comment]
It is unclear what your intentions are exactly. Could you create a repository with a reproduction of the bug? That is much easier to debug then these steps to reproduce.

**Comment by B4nan** [comment]
I was just about to write the same but realized what the issue is about. The decorator wrapes given method but it won't return its return value. 

The return value is ignored on this line: https://github.com/mikro-orm/nestjs/blob/4e0bad0ffb36cfb3802a3eda4ec2272e33341d82/src/mikro-orm.common.ts#L22

Anyway, next time please share some code when filing a bug report, this is not the right way to do it...

**Comment by SimoneDagna** [comment]
The "problem" is also in `RequestContext` class from Mikro-Orm project:
https://github.com/mikro-orm/mikro-orm/blob/7e7427335a005bb379509a9a9e86a01c44a21e07/packages/core/src/utils/RequestContext.ts#L37-L42

the return type is `Promise<void>`, so even modifying the line: 
https://github.com/mikro-orm/nestjs/blob/4e0bad0ffb36cfb3802a3eda4ec2272e33341d82/src/mikro-orm.common.ts#L22
the `UseRequestContext` decorator will be unable to return the original method result.

**Comment by jearangoo** [comment]
can this fix be included into a new version in npm?

**Comment by B4nan** [comment]
Oh right, forgot to release it - I don't have time for this right now but will ship it early next week.

But the method is really a simple one, nothing special in it, so you can just copy the code to your project and use your (fixed) implementation instead.
