### ISSUE TITLE
RequestContext example for GraphQL

### ISSUE THREAD

**Issue by babsonmatt** [mikro-orm/nestjs#22]
**Is your feature request related to a problem? Please describe.**
I'm using GraphQL with NestJS but noticing that the same entity manager is being used for all requests and I'm not sure how to proceed with establishing a new context per request.

**Describe the solution you'd like**
It'd be great if this library just worked out of the box with NestJS GraphQL but if not maybe some example code would be great to help people get started.

Thanks!

**Comment by B4nan** [comment]
There is this one here:

https://github.com/driescroons/mikro-orm-graphql-example

Can't help more, never really used GQL myself 🤷

**Comment by B4nan** [comment]
There is also this: https://github.com/MichalLytek/type-graphql/tree/v1.1.1/examples/mikro-orm

**Comment by babsonmatt** [comment]
@B4nan thanks haha, I saw those but I'm looking for an example more specific to graphql + nestjs (it seems much more straightforward with graph or nestjs on their own)

**Comment by roderik** [comment]
I just hit the same issue. @babsonmatt did you find a workable approach?

**Comment by B4nan** [comment]
> injected repositories are shared (_em: [EntityManager<1>],)

This is normal/expected, in fact the `RequestContext` is there to allow using singletons (global EM and its attached repository instances). Under the hood the correct EM is taken via `em.getContext()` where needed.

**Comment by B4nan** [comment]
Actually I though I already did some debugging with this apollo vs request context issue. And indeed I was right, and there was someone who managed to debug it and found the cause:

https://github.com/mikro-orm/mikro-orm/issues/696#issuecomment-669846919

> The trouble with apollo-server-express seems is because it include and enable by default body-parser.
>
> if disabling body-parser in apollo-server-express and handle it manually before RequestContext all seems work well:
>
> ```
> application.use("/", bodyParser.json());
> application.use((_req, _res, next) => RequestContext.create(DI.orm.em, next));
> apolloServer.applyMiddleware({ app: application, path: "/", bodyParserConfig: false });
> ```

**Comment by roderik** [comment]
Ok, it works!

You can do the changes in the previous comment as follows.

main.ts
```
import { NestFactory } from '@nestjs/core';
import bodyParser from 'body-parser';

async function bootstrap() {
  const app = await NestFactory.create(LaunchpadModule);
  app.use(bodyParser.json());
  await app.listen(5555);
}
```

app.module.ts
```
@Module({
  imports: [
    MikroOrmModule.forRootAsync({
      imports: [StrictConfigModule],
      inject: [StrictConfigService],
      useFactory: (configService: StrictConfigService) => configService.getMongoSettings(),
    }),
    GraphQLModule.forRootAsync({
      imports: [StrictConfigModule, OgmaModule, AuthModule],
      inject: [StrictConfigService, AuthService],
      useFactory:() => {
		    {
				...
		          bodyParserConfig: false,
				...
		          },
		        };
		      },
    }),
  ],
  controllers: [],
  providers: [],
})
```

**Comment by woltob** [comment]
@roderik thank you for your input. 
We are also running NestJS with Apollo GraphQL and we could not get the per Request Identity Map  / Entity Manager to work. Could you please provide use with a small repo (or just one file that shows the config) that display how this is achieved? It is a major blocker currently. 
Any hints to other code bases are also appreciated.
Thanks!!

**Comment by roderik** [comment]
> @roderik thank you for your input.
> We are also running NestJS with Apollo GraphQL and we could not get the per Request Identity Map / Entity Manager to work. Could you please provide use with a small repo (or just one file that shows the config) that display how this is achieved? It is a major blocker currently.
> Any hints to other code bases are also appreciated.
> Thanks!!

my last comment has the fix

disable bodyparser in GraphQLModule.forRootAsync, then manually enable it again after the app is initialised like so using   app.use(bodyParser.json());

**Comment by B4nan** [comment]
It is also described in the docs:

https://mikro-orm.io/docs/usage-with-nestjs#request-scoping-when-using-graphql
