### ISSUE TITLE
Custom repository injection without naming convention

### ISSUE THREAD

**Issue by EricMcRay** [mikro-orm/nestjs#25]
**Is your feature request related to a problem? Please describe.**
I am replacing typeorm with mikro-orm for a project. I replaced all decorators and repositories but just one repository didn't work. After my 4 hour struggle, I realized that I have a typo in the repository name. 

**Describe the solution you'd like**
I am not nestjs pro but inject and resolve repositories from `@Entity` decorators `customRepository` or `EntityRepositoryType` symbol would be nice.

**Describe alternatives you've considered**
Get repository from entity manager 

**Additional context**
And in the custom repository examples [document](https://mikro-orm.io/docs/repositories/#custom-repository) entity and repository names not like nestjs required naming convention so this can be misleading

**Comment by B4nan** [comment]
I literally have no idea what you are asking for. Please provide some examples and be more verbose. 

But don't expect MikroORM decorators or options to have any effect on how nest DI work, that won't be an option, I can say that right ahead.

**Comment by EricMcRay** [comment]
basicly; getting rid of `getRepositoryToken()` mentioned in https://mikro-orm.io/docs/usage-with-nestjs#using-custom-repositories.

**Comment by B4nan** [comment]
How do you expect that to work? All services in nest DI need to have a name. This has nothing to do with MikroORM or its integration, this is how nest works.
