### ISSUE TITLE
Add Nest 8 support

### ISSUE THREAD

**Issue by msheakoski** [mikro-orm/nestjs#27]
Nest 8 was released recently: https://github.com/nestjs/nest/releases/tag/v8.0.0

~~At first glance, it does not look like there are any breaking changes that would affect this package, so probably just the dependencies need to be updated in package.json~~

@mekwall [is correct](https://github.com/mikro-orm/nestjs/issues/27#issuecomment-877275940) that there seems to be a problem with dependency injection due to Nest 8 using the instance vs name.

**Comment by inglkruiz** [comment]
I did face a small issue in my Unit tests after upgrading to Nest 8. I used to get Repository classes using

**Comment by msheakoski** [comment]
@inglkruiz Have you tried with getRepositoryToken?

```typescript
import { EntityRepository } from "@mikro-orm/postgresql"
import { getRepositoryToken } from "@mikro-orm/nestjs"

const usageRepository = app.get<EntityRepository<Usage>>(getRepositoryToken(Usage))
```

**Comment by mekwall** [comment]
I am pretty certain that the changes introduced in [this PR](https://github.com/nestjs/nest/pull/6141) broke the dependency injection of this package.

**Comment by Nisgrak** [comment]
I am using in Nest 8 and works so far

**Comment by jearangoo** [comment]
i can't install with nestjs version 8  `npm i -s @mikro-orm/nestjs --verbose`

``` 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: server@0.0.1
npm ERR! Found: @nestjs/common@8.0.2
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"8.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^7.0.0" from @mikro-orm/nestjs@4.2.0
npm ERR! node_modules/@mikro-orm/nestjs
npm ERR!   @mikro-orm/nestjs@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

```

**Comment by Nisgrak** [comment]
Install with `--force`, we need to update at least the peerDependecies (would be great to rush that, then works in the reported bugs)

**Comment by notmedia** [comment]
@B4nan Hi, any news?)

**Comment by Maikuh** [comment]
Injecting Repositories seem to work fine, but injecting `EntityManager` (from `@mikro-orm/postgresql` to be specific) does not.

I get the following error:
```
Nest can't resolve dependencies of the RentalService (?, RentalRepository). Please make sure that the argument SqlEntityManager at index [0] is available in the RentalModule context.

Potential solutions:
- If SqlEntityManager is a provider, is it part of the current RentalModule?
- If SqlEntityManager is exported from a separate @Module, is that module imported within RentalModule?
  @Module({
    imports: [ /* the Module containing SqlEntityManager */ ]
  })
```

**Comment by ltudisco** [comment]
I am experiencing the same issue @Maikuh is experiencing after upgrading to NestJS 8.

**Comment by Dudrie** [comment]
I am experiencing the same issue as @Maikuh but is use the `@mikro-orm/mysql` package instead of the postgresql one.

**Comment by JoelVenable** [comment]
Any progress on this?  I'm having an issue with custom repositories that extend from EntityRepository<MyModel>.  Basically, any custom methods that I define are coming back `undefined` at runtime...

**Comment by B4nan** [comment]
v4.3 stable is out

**Comment by EduVencovsky** [comment]
> v4.3 stable is out

Does this means that only upgrading to v4.3 or higher will make it work?

Because I updated to the lasted version available (4.5.9) but I'm still getting the error

>Nest can't resolve dependencies of the MikroOrmCoreModule (Symbol(mikro-orm-module-options), ?). Please make sure that the argument ModuleRef at index [1] is available in the MikroOrmCoreModule context.

Is there any other step to make it work? If there is, please explain or add to some docs, otherwise it can be some other mistake I made while updating nest

**Comment by behalka** [comment]
I am also still experiencing this issue with 4.3

**Comment by B4nan** [comment]
This issue is already addressed, if you experience something similar, please open new issue with full reproduction.

**Comment by msheakoski** [comment]
I can confirm, no issues with this since v4.3 in August. Try deleting your node_modules dir and reinstalling packages.

**Comment by behalka** [comment]
thank you, was just about to update my comment, it is probably because of `pnpm` install, as mentioned in #41

**Comment by B4nan** [comment]
Will try to test it with pnpm too, but I am a bit overloaded these days.

**Comment by behalka** [comment]
In the meantime, as workaround, we could use `EntityManager` from `@mikro-orm/knex`. As you said, it is the same thing, just reexported and the DI works as expected 🙂  Thank you for your time!

**Comment by kestereverts** [comment]
To those experiencing this issue since upgrading to NestJS 8, using `yarn`, but not using `pnpm`: I was able solve the problem by matching the `mysql2` dependency version in my project's `package.json` with the one used by `@mikro-orm/mysql-base`.

Not doing so will cause package-local installs of `@mikro-orm/knex` instead of a single global one, effectively breaking NestJS's DI. It wasn't a problem with NestJS 7 because it identified DI based on a string value (the class constructor's name) rather than a real reference to a class.

**Comment by B4nan** [comment]
Just came across [this issue](https://github.com/pnpm/pnpm/issues/3917) regarding pnpm - worth checking if the installation of `@mikro-orm/knex` package helps.

> I was able solve the problem by matching the mysql2 dependency version in my project's package.json with the one used by @mikro-orm/mysql-base.

You should not install that package yourself (unless you work with it directly, not via the ORM). It is no longer a peer depedency - just install `@mikro-orm/mysql` that includes it in its direct dependencies.
