### ISSUE TITLE
Injected EntityRepository has the same EntityManager on every request

### ISSUE THREAD

**Issue by TLmaK0** [mikro-orm/nestjs#31]
**Describe the bug**
I'm not sure that this is an incorrect behavior. When print EntityRepository from a controller action, it always return the same EntityManager:

```
SqlEntityRepository { _em: [EntityManager<1>], entityName: 'Book' }
[Nest] 35606   - 08/03/2021, 10:59:57 AM   [MikroORM] [query] select `e0`.* from `author` as `e0` where `e0`.`id` = 1 limit 1 [took 1 ms]
[Nest] 35606   - 08/03/2021, 10:59:57 AM   [MikroORM] [query] select `e0`.* from `book` as `e0` where `e0`.`author_id` in (1) order by `e0`.`author_id` asc [took 1 ms]
SqlEntityRepository { _em: [EntityManager<1>], entityName: 'Book' }
[Nest] 35606   - 08/03/2021, 11:06:18 AM   [MikroORM] [query] select `e0`.* from `author` as `e0` where `e0`.`id` = 1 limit 1 [took 1 ms]
[Nest] 35606   - 08/03/2021, 11:06:18 AM   [MikroORM] [query] select `e0`.* from `book` as `e0` where `e0`.`author_id` in (1) order by `e0`.`author_id` asc [took 1 ms]
```

but mikro-orm middleware creates a new context in every request, so a fork of EntityManager is created:

```
RequestContext { map: Map { 'default' => [EntityManager<2>] }, id: 1 }
SqlEntityRepository { _em: [EntityManager<1>], entityName: 'Book' }
[Nest] 38056   - 08/03/2021, 11:11:37 AM   [MikroORM] [query] select `e0`.* from `author` as `e0` where `e0`.`id` = 1 limit 1 [took 2 ms]
[Nest] 38056   - 08/03/2021, 11:11:37 AM   [MikroORM] [query] select `e0`.* from `book` as `e0` where `e0`.`author_id` in (1) order by `e0`.`author_id` asc [took 1 ms]
RequestContext { map: Map { 'default' => [EntityManager<3>] }, id: 2 }
SqlEntityRepository { _em: [EntityManager<1>], entityName: 'Book' }
[Nest] 38056   - 08/03/2021, 11:11:41 AM   [MikroORM] [query] select `e0`.* from `author` as `e0` where `e0`.`id` = 1 limit 1 [took 5 ms]
[Nest] 38056   - 08/03/2021, 11:11:41 AM   [MikroORM] [query] select `e0`.* from `book` as `e0` where `e0`.`author_id` in (1) order by `e0`.`author_id` asc [took 3 ms]
```

In my project I when some request fail and request again, the last entity added with fail to the EntityManager exists in the new request. So my concern is that the EntityRepository is not changing to new fork of the EntityManager.

I'm trying to reproduce this behavior in the project https://github.com/mikro-orm/nestjs-example-app and I have the same EntityManager for every request (described in the logs), but the repo doesn't have the entities added in the last failed request.

Is this EntityManager behavior correct?

**Comment by B4nan** [comment]
You work with the global instances, that is the whole point of `RequestContext` helper. Internally the fork is used, you can access it via `em.getContext()`.

**Comment by TLmaK0** [comment]
@B4nan Do you have any idea why in every request my folders collection increase by one? I'm not calling `flush`, so it doesn't persist to db.
This is my controller:

```Typescript
import {Controller, Post} from "@nestjs/common";   
import {Folder, Bucket} from "../domain";                    
import {InjectRepository} from '@mikro-orm/nestjs';
import {EntityRepository} from '@mikro-orm/core';                                   
                                                                                     
@Controller()                                                                       
export class FolderController {   
  constructor(                    
    @InjectRepository(Bucket) private readonly bucketsRepo: EntityRepository<Bucket>,   
  ) {}                                                                                  
         
  @Post('folders')   
  async createFolder(   
  ) {                   
    const folder = new Folder({name: 'test'});   
    const bucket = await this.bucketsRepo.findOne({companyId: '1'}, ['folders']);   
                                                                                    
    bucket.folders.add(folder);   
    this.bucketsRepo.persist(bucket);   
    console.log(bucket.folders);        
    //await this.bucketsRepo.flush();   
  }                                     
}     
```
Thanks for your help

**Comment by B4nan** [comment]
idk, enable debug mode, if you see insert queries, you are flushing somewhere. might be really misconfigured request context.

also note that there is reason to persist managed entities, flush will always go thru all managed entities. another note - flush is an action of UoW, both persist and flush on repository is just a shortcut, you always work with the EM, repository is just a think layer on top of it (more of an extension point). 

you could add console.logs to the ORM code to flush method to see from where it is called (just log `new Error().stack`)

**Comment by TLmaK0** [comment]
Thanks @B4nan. There aren't any "insert" in the logs (the table is empty). I will try to create a project to reproduce it.

**Comment by B4nan** [comment]
Well, if you dont see any insert queries in logs, then its not the ORM who does it. Or maybe I misunderstood what you mean by "in every request my folders collection increase by one".

**Comment by TLmaK0** [comment]
I mean, when I call `console.log(bucket.folders)` inside the controller, it prints one more folder in every request, but there isn't any folder in the table.

```
[query] select "e0".* from "bucket" as "e0" where "e0"."id" = '1' limit 1 [took 3 ms]
[query] select "e0".* from "folder" as "e0" where "e0"."bucket_id" in ('1') order by "e0"."bucket_id" asc [took 3 ms]
Collection {
  '0': Folder {
    name: 'test',
    bucket: Bucket { id: '1', name: 'asdfasdf', folders: [Collection] }
  },
  initialized: true,
  dirty: true
}
Collection {
  '0': Folder {
    name: 'test',
    bucket: Bucket { id: '1', name: 'asdfasdf', folders: [Collection] }
  },
  '1': Folder {
    name: 'test',
    bucket: Bucket { id: '1', name: 'asdfasdf', folders: [Collection] }
  },
  initialized: true,
  dirty: true
}
Collection {
  '0': Folder {
    name: 'test',
    bucket: Bucket { id: '1', name: 'asdfasdf', folders: [Collection] }
  },
  '1': Folder {
    name: 'test',
    bucket: Bucket { id: '1', name: 'asdfasdf', folders: [Collection] }
  },
  '2': Folder {
    name: 'test',
    bucket: Bucket { id: '1', name: 'asdfasdf', folders: [Collection] }
  },
  initialized: true,
  dirty: true
}
```

**Comment by B4nan** [comment]
That really looks like misconfigured request context. As I already said in the very first reply, you can verify it via `em.getContext().id`, so ensure you have different ids for each request. 

Are you testing this via regular requests or is it some unit/integration test? Does it work the same if you work with EM instead of repositories?

I can assure you there is no problem with the request context class itself, if the issue is with that, it points to misconfiguration. If there was a bug in such a fundamental part, there would be many many more issues like that :] Its code is very trivial, there is not much that could be broken.

**Comment by B4nan** [comment]
Wild guess, but common source of weird issues is having misaligned package versions. All ORM packages need to be on the very same version, only exceptions are the nest package and highlighters.

**Comment by TLmaK0** [comment]
Many thanks @B4nan, I will try to review package versions. This is what I get from em.getContext().id:

```Typescript
import {Controller, Post} from "@nestjs/common";
import {Folder, Bucket} from "../domain";
import {InjectRepository} from '@mikro-orm/nestjs';
import {EntityRepository} from '@mikro-orm/core';

@Controller()
export class FolderController {
  constructor(
    @InjectRepository(Bucket) private readonly bucketsRepo: EntityRepository<Bucket>,
  ) {}

  @Post('folders')
  async createFolder(
  ) { 
    const folder = new Folder();
    folder.name = 'test';
    const bucket = await this.bucketsRepo.findOne('1', ['folders']);

    bucket.folders.add(folder);
    this.bucketsRepo.persist(bucket);
    console.log(this.bucketsRepo['_em'].getContext().id);
    //await this.bucketsRepo.flush();
  }
}
```

multiple requests returns
```
[query] select "e0".* from "bucket" as "e0" where "e0"."id" = '1' limit 1 [took 3 ms]
[query] select "e0".* from "folder" as "e0" where "e0"."bucket_id" in ('1') order by "e0"."bucket_id" asc [took 2 ms]
1
1
1
1
1
1
```

**Comment by B4nan** [comment]
Yeah thats definitely wrong. Try to compare what you are doing differently from the example project, as there the request context is setup properly.

**Comment by TLmaK0** [comment]
Thanks @B4nan. Finally I found the problem. I use FastifyAdapter, removing it from the app it works as expected, so there is something wrong with @mikro-orm/nestjs and Fastify. Here is a repo to test it https://github.com/proptex/nestjs-fastify-mikro-orm. If you comment the line 30 from `FolderController.ts`, you will get the same result without inserts in the database. Removing FastifyAdapter from line 13 in `main.ts` will work as expected. If it is a bug, I can help to try to fix it, but I need help to start.

**Comment by B4nan** [comment]
Check this PR, the detection is probably not working or they made some BC again

https://github.com/mikro-orm/nestjs/pull/4

**Comment by TLmaK0** [comment]
@B4nan the `createDomain()` from `RequestContext` is called in every request, but the problem is that in  `RequestContext.currentRequestContext()` https://github.com/mikro-orm/mikro-orm/blob/v4.5.7/packages/core/src/utils/RequestContext.ts#L48, active is undefined when use FastifyAdapter. Any thoughts?

**Comment by B4nan** [comment]
I already told you where to look, this is not about `RequestContext` class, this is about the middleware that is using it. See the PR #4 and check the fastify detection that is added there.

**Comment by TLmaK0** [comment]
I have checked and `usingFastify(consumer)` returns true, also forRoutesPath returns '(.*)' which is correct.

**Comment by TLmaK0** [comment]
This is the explanation of the behavior I found in the repro: https://github.com/proptex/nestjs-fastify-mikro-orm.

With FastifyAdapter, Fastify tries to parse the content:

https://github.com/fastify/fastify/blob/8371ba04d6ee8fb320ae1535233b3a999882fe3c/lib/contentTypeParser.js#L203 here domain.active is correct.

https://github.com/fastify/fastify/blob/8371ba04d6ee8fb320ae1535233b3a999882fe3c/lib/contentTypeParser.js#L221 now domain.active is undefined. 

If domain.active is undefined, `RequestContext.getEntityManager()` returns undefined, then `Configuration<D extends IDatabaseDriver = IDatabaseDriver>.context` returns undefined too.

In EntityManager when try to `getContext` https://github.com/mikro-orm/mikro-orm/blob/3dd9f7717667675065d9affa12e02d87fa7a25a2/packages/core/src/EntityManager.ts#L824 there is:

```
em = this.useContext ? (this.config.get('context')(this.name) || this) : this;
```

which will use the current EntityManager instead of reuse the last created in RequestContext.

**Comment by TLmaK0** [comment]
@B4nan I think we should reopen the issue. I have tested it with other node versions and I can reproduce the same problem with the repro. I was not able to make it work with Fastify (no problems with express). I think the issue is the use of "domain" that is being deprecated. It could be that some one has a workaround.

**Comment by B4nan** [comment]
I did try to use the fastify adapter with the realworld example, and it works just fine for me, no issues with request contexts. The only endpoint that was not working was the one for favoriting articles, which is probably caused by some difference in routing (as the endpoint is not reachable from tests and returns 400, rest of them work just fine).

**Comment by Mitch-i** [comment]
This is the end, a bug that live 4 month.
