### ISSUE TITLE
Support connect argument from MikroORM.init()

### ISSUE THREAD

**Issue by grimurd** [mikro-orm/nestjs#35]
**Is your feature request related to a problem? Please describe.**

When testing it can be useful to initial MikroORM without connecting to a database. MikroORM supports this through the [connect argument in MikroORM.init()](https://mikro-orm.io/docs/api/classes/core.mikroorm#init).

Currently the nestjs module doesn't support this. 

**Describe the solution you'd like**

Either add a argument to MikroORMModule.forRoot()/forRootAsync() or add it to the module options object.

**Comment by B4nan** [comment]
`connect` will be a regular configuration option too since v5.0.3 of the ORM (no changes in the nest adapter, just upgrade the ORM)
