### ISSUE TITLE
Add a standard interceptor for the transformation of instance into POJO

### ISSUE THREAD

**Issue by H6LS1S** [mikro-orm/nestjs#37]
For most simple CRUDs don't often have to resort to mapping the entity via the response DTO, but often need to hide fields in the entity using mikro-orm or decorators from the `class-transformer` library. All this leads to writing similar code for the service (see below). This typing causes nestjs plugins working with Abstract Syntax Tree analysis, such as - `@nestjs/swagger/plugin`, to simply break, and fail to generate the API schema
```ts
...

  public async create(data: CreateUserDto): Promise<EntityData<UserEntity>> {
    const entity = this.sqlEntityRepository.create(data);
    await this.sqlEntityRepository.persistAndFlush(entity)
    return entity.toPOJO();
  }

...
```

The proposed version of serialization works before the serializer nestjs and gives the prepared class further down the call chain (the order of interceptor calls is important) without breaking service typing and does not require creating a DTO response
```ts
// mikro-orm-serializer.interceptor.ts
import { isObject } from '@nestjs/common/utils/shared.utils';
import { BaseEntity } from '@mikro-orm/core';
import { map, Observable } from 'rxjs';
import {
  Injectable,
  CallHandler,
  StreamableFile,
  NestInterceptor,
  ExecutionContext,
  PlainLiteralObject,
} from '@nestjs/common';

@Injectable()
export class MikroOrmSerializerInterceptor implements NestInterceptor {

  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    return next
      .handle()
      .pipe(map((res: PlainLiteralObject | Array<PlainLiteralObject>) => this.serialize(res)));
  }

  /**
   * Serializes responses that are non-null objects nor streamable files.
   */
  serialize(
    response: PlainLiteralObject | Array<PlainLiteralObject>,
  ): PlainLiteralObject | Array<PlainLiteralObject> {
    if (!isObject(response) || response instanceof StreamableFile) return response;
    return Array.isArray(response)
      ? response.map((item) => this.transformToPOJO(item))
      : this.transformToPOJO(response);
  }

  /**
   * Transformation to POJO if argument is a BaseEntity instance
   */
  transformToPOJO(plainOrEntity: any): PlainLiteralObject {
    return plainOrEntity instanceof BaseEntity ? plainOrEntity.toPOJO() : plainOrEntity;
  }
}
```

- Use as a global interceptor in conjunction with ClassSerializerInterceptor
```ts
//main.ts
   ...

  const classSerializerInterceptor = new ClassSerializerInterceptor(app.get(Reflector));
  const mikroOrmSerializerInterceptor = new MikroOrmSerializerInterceptor();

  return app
    .useGlobalInterceptors(classSerializerInterceptor, mikroOrmSerializerInterceptor)
    .listen(configService.get('PORT'), configService.get('HOST'));
```

Alternatively, can rewrite all logic related to metadata reflection using the `class-transformer` library
> But I don't think that's a good option for upcoming releases

**Comment by H6LS1S** [comment]
@B4nan. It all started when I noticed fields in the API response that were marked as `hidden: true` in entity. After that I started trying different serialization methods, and only `toPOJO` was suitable for sharing with `class-transformer`

**Comment by B4nan** [comment]
>  it does not call JSON.stringify anywhere

It (fastify) definitely does call it (see https://github.com/fastify/fastify/blob/main/lib/schema-compilers.js and https://github.com/fastify/fast-json-stringify/blob/master/index.js#L900-L905, it uses its own helper to do this, but it works the very same way), at the very last stage, as JSON string is what you transfer over http, not objects. Your problem is that you want to work with POJO before it gets transformed to the actual response.

This really feels like something you should have in your own project.
