### ISSUE TITLE
Please make sure that the argument SqlEntityManager at index [1] is available in the AppModule context.

### ISSUE THREAD

**Issue by rizchaerul** [mikro-orm/nestjs#40]
**Describe the bug**
I got this error when injecting EntityManager from @mikro-orm/postgresql. Right now my solution is just to import EntityManager from @mikro-orm/knex or @mikro-orm/core and it can run without error. But earlier when i tried MikroORM v5, i got the same error when importing from @mikro-orm/knex. Now the only one that works is from @mikro-orm/core.

![image](https://user-images.githubusercontent.com/72289631/138608232-5126a787-0de7-46f2-8bf5-4a7be30ad80b.png)

**To Reproduce**
1. Create new nestjs project
2. Install MikroORM dependency (https://mikro-orm.io/docs/next/usage-with-nestjs/#installation)
3. Register MikroORM module in AppModule
![image](https://user-images.githubusercontent.com/72289631/138608462-4b6a70f7-5279-4816-88d5-cc648e57ca1e.png)
4. Inject EntityManager from @mikro-orm/postgresql
![image](https://user-images.githubusercontent.com/72289631/138608518-d157d694-3713-4b8b-8a8a-9cf6957cae04.png)

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| nestjs| ^8.1.1 |
| typescript | ^4.4.4 |
| mikro-orm | ^4.5.9 |
| your-driver | postgresql |

**Comment by stefansundin** [comment]
This error also happens if you have `pg` as a dependency in `package.json` and it doesn't match what `@mikro-orm/postgresql` wants. Make sure that the versions match!
