### ISSUE TITLE
Load EntitySchema

### ISSUE THREAD

**Issue by rjlopezdev** [mikro-orm/nestjs#50]
Is it possible to load `EntitySchemas` the way `Entities` are loaded at `MikroOrmModule`?
How could it be done?

Use Case:

```ts
export const fooSchema = new EntitySchema<Foo>({
  class: Foo,
  properties: {
    id: { type: 'uuid', primary: true },
    name: { type: 'string' },
  },
});
```

```ts
  imports: [MikroOrmModule.forFeature(/* ??? */)],
```

**Note**: Foo is a plain class (not annotated with `@Entity` decorator)

**Comment by B4nan** [comment]
`forFeature` is not for loading entities, it just registers repositories. it should work the very same way, just put the entity class in there (and it will probably work with entity schema instance too). `forFeature` accepts a string name or any object with `name` property (both class and entity schema instance works this way).
