### ISSUE TITLE
Importing EntityManager fails when using webpack

### ISSUE THREAD

**Issue by sayav** [mikro-orm/nestjs#57]
**Describe the bug**
I've got an issue with webpack not being able to dynamically import '@mikro-orm/knex' or '@mikro-orm/mongodb' in the `whenModuleAvailable` function. Since these are imported as enums (e.g. `import(EntityManagerModuleName.Knex)`) webpack does not bundle these modules. It's possible to fix this by importing with strings `import("@mikro-orm/knex")`. I can write a pull request if this would help :)

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 4.1.6 |
| mikro-orm | 5.x |

**Comment by B4nan** [comment]
Feel free to PR this, this particular piece of code also came from someone else, I don't really like that enum there anyway.

**Comment by B4nan** [comment]
Will you have time for this during today? I'd like to ship v5 in few hours, will be happy to look into it myself right now, if you haven't started already.

**Comment by sayav** [comment]
I can have it done today for sure

**Comment by B4nan** [comment]
Already started, so will push what I have in a minute and feel free to improve on that :]

**Comment by sayav** [comment]
Oh sorry I missed that message. Feel free to look at the pull request.

**Comment by B4nan** [comment]
I see we ended up with quite similar approach, mine being a less verbose I guess.
