### ISSUE TITLE
How to use entity repository in service without injecting

### ISSUE THREAD

**Issue by Quadriphobs1** [mikro-orm/nestjs#6]
The mikro-orm docs have a way to create a repository https://mikro-orm.io/docs/next/repositories however from the documentations and example there has been no way to use the repository like you would in typeorm

```
@Repository(Author)
export class CustomAuthorRepository extends EntityRepository<Author> {

  // your custom methods...
  public findAndUpdate(...) {
    // ...
  }

}
```

**Comment by B4nan** [comment]
You define the custom repository, and it will be used automatically. If you use `@Repository()` decorator, you need to make sure the file will be loaded, so the decorator can be executed (without that, the ORM does not know about such repository). 

One way to make sure the file will be loaded is to link it from the entity definition. To do so, you can use `EntityRepositoryType`, that will also allow inference of the type of the repository:

```ts
@Entity()
export class Author {

  [EntityRepositoryType]: CustomAuthorRepository;

}
```

Now this ensures the `@Repository()` decorator will be executed and custom repository will be registered. The `em.getRepository(Author)` will be correctly typed to `CustomAuthorRepository`. 

```ts
constructor(
  @InjectRepository(Author)
  private readonly articleRepository: CustomAuthorRepository,
) {}
```

**Comment by Quadriphobs1** [comment]
Hmmm... Having to go through the @InjectResitory seems a little bit overly roundtrip to me, I was actually hoping for a way to either register it through the module as a provider or something just as services can be registered using the provider

**Comment by B4nan** [comment]
I still don't follow what you mean. So you don't like the `InjectRepository` bit, but are fine with using nest DI in general? You can make the repository injectable, the decorator is needed only when you do not have custom implementation. 

This is how the repositories are registered, you can use the same way to register your custom repository:

https://github.com/mikro-orm/nestjs/blob/master/src/mikro-orm.providers.ts#L63

```ts
{
  provide: CustomAuthorRepository, 
  useFactory: (em: EntityManager) => em.getRepository(Author),
  inject: [EntityManager],
}
```

Or as long as you name your custom repository the same way as [`getRepositoryToken()`](https://github.com/mikro-orm/nestjs/blob/ba01e1e33454cdb1e7f09a271ae23c9b4fb15f21/src/mikro-orm.common.ts#L6) helper would, you don't need to do anything special:

```ts
@Repository()
export class AuthorRepository ... {}

constructor(private repo: AuthorRepository) {}
```

**Comment by Quadriphobs1** [comment]
Ohhh that seems better... Having to put the decorator on the repository is what I was actually concerned about...  but removing also do the trick...

**Comment by nikkonrom** [comment]
Is there any way to specify `[EntityRepositoryType]: CustomAuthorRepository;` while defining entities through `EntitySchema`?

**Comment by B4nan** [comment]
Just put it to the class/interface:

```ts
export interface IAuthor4 {
  [EntityRepositoryType]: AuthorRepository;
  id: number;
  name: string;
  email: string;
}

export const Author4 = new EntitySchema<IAuthor4>({
  name: 'Author4',
  properties: {
    id: { type: 'number', primary: true },
    name: { type: 'string' },
    email: { type: 'string', unique: true },
  },
  customRepository: () => AuthorRepository,
});
```

You need both, `EntityRepositoryType` is for TS inference, `customRepository` is for the ORM runtime metadata.

**Comment by mrfsbDev** [comment]
Does nestjs work the same way?
