### ISSUE TITLE
Custom repositories not sharing the same request scoped Entity Manager

### ISSUE THREAD

**Issue by christiaan-lombard** [mikro-orm/nestjs#67]
**Describe the bug**
When injecting both the EntityManager and a custom repository I noticed that the EntityManager bound to the repository is not the same EntityManager. I expect to always get the same EntityManager for a given request.

```ts
@Injectable()
export class CatService {
  constructor(
    public readonly em: EntityManager,
    public readonly repo: CatRepository,
  ) {}

  compareEntityManagers() {
    return this.em.id === this.repo.getEntityManager().id; // expect this to be true
  }
}
``` 

**Stack trace**
```
...
```

**To Reproduce**
1. Clone repository [github.com/christiaan-lombard/nestjs-mikro-orm-test](https://github.com/christiaan-lombard/nestjs-mikro-orm-test)
2. `npm install`
3. `docker-compose up` to start up a mysql instance
4. `npm run test` to run test src/app.module.spec.ts

**Expected behavior**
I would like to be able to inject both custom repositories and the EntityManager in a service and have them share the same EntityManager for the current request.

I expect the following test to pass:
```ts
import { EntityManager } from '@mikro-orm/mysql';
import { ContextId, ContextIdFactory } from '@nestjs/core';
import { REQUEST_CONTEXT_ID } from '@nestjs/core/router/request/request-constants';
import { Test, TestingModule } from '@nestjs/testing';
import { AppModule } from './app.module';
import { Cat } from './entities/cat.entity';
import { CatRepository } from './repositories/cat.repository';

describe('AppModule', () => {
  let module: TestingModule;
  let contextId: ContextId;

  beforeAll(async () => {
    module = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    contextId = ContextIdFactory.create();

    module.registerRequestByContextId(
      { [REQUEST_CONTEXT_ID]: contextId },
      contextId,
    );
  });

  afterAll(async () => await module.close());

  it('resolves same EntityManager', async () => {
    const em = await module.resolve<EntityManager>(EntityManager, contextId);
    const em2 = await module.resolve<EntityManager>(EntityManager, contextId);

    expect(em.id).toBe(em2.id);
    expect(em).toStrictEqual(em2);
  });

  it('resolves same EntityManager for repositories created by EM', async () => {
    const em = await module.resolve<EntityManager>(EntityManager, contextId);
    const repo = em.getRepository(Cat);
    expect(repo).toBeInstanceOf(CatRepository);
    expect(em.id).toBe(repo.getEntityManager().id);
    expect(em).toStrictEqual(repo.getEntityManager());
  });

  it('resolves same EntityManager for repositories', async () => {
    const em = await module.resolve<EntityManager>(EntityManager, contextId);
    const repo = await module.resolve<CatRepository>(CatRepository, contextId);

    expect(em.id).toBe(repo.getEntityManager().id); // fails
  });
});

```

**Versions**

| Dependency | Version |
| - | - |
| node | v16.13.0 |
| typescript | ^4.3.5 |
| mikro-orm | ^5.1.0 |
| nestjs | ^8.0.0 |

**Comment by B4nan** [comment]
Which part fails? Comparing the instances is wrong, they should not be the same, you should compare just the `em.id`.

**Comment by duplessisbabylonstoren** [comment]
@B4nan I believe the part that fails is the very last test: `expect(em.id).toBe(repo.getEntityManager().id);`

**Comment by christiaan-lombard** [comment]
@B4nan I am comparing the EMs by `id` and by reference. I will comment below what fails and passes:

```ts
  // passes: returns the same entity manager (by object reference) when injecting 2 entity managers
  it('resolves same EntityManager', async () => {
    const em = await module.resolve<EntityManager>(EntityManager, contextId);
    const em2 = await module.resolve<EntityManager>(EntityManager, contextId);

    expect(em.id).toBe(em2.id);
    expect(em).toStrictEqual(em2);
  });

  // passes: the EM is just passed to the repository so this obviously passes
  it('resolves same EntityManager for repositories created by EM', async () => {
    const em = await module.resolve<EntityManager>(EntityManager, contextId);
    const repo = em.getRepository(Cat);
    expect(repo).toBeInstanceOf(CatRepository);
    expect(em.id).toBe(repo.getEntityManager().id);
    expect(em).toStrictEqual(repo.getEntityManager());
  });

  // fails: repository is not injected with the same EM as what is provided with the EntityManager token
  it('resolves same EntityManager for repositories', async () => {
    const em = await module.resolve<EntityManager>(EntityManager, contextId);
    const repo = await module.resolve<CatRepository>(CatRepository, contextId);

    expect(em.id).toBe(repo.getEntityManager().id); // fails
  });
```

The repository I referenced previously ([github.com/christiaan-lombard/nestjs-mikro-orm-test](https://github.com/christiaan-lombard/nestjs-mikro-orm-test)) has all the context and configuration to run the above test.

My suspicion as to what might be causing this is the fact that the [MikroOrmCoreModule](https://github.com/mikro-orm/nestjs/blob/master/src/mikro-orm-core.module.ts) provides the EntityManager from a global context; whereas the [MikroOrmModule](https://github.com/mikro-orm/nestjs/blob/master/src/mikro-orm.module.ts) provides entity repositories and likely injects the EntityManager from a different context.

**Comment by B4nan** [comment]
FYI everything in the DI container are global instances. They will work with the context under the hood, as well as the `em.id` will respect it (check the code, its a getter that actually gives you `this.getContext().id`).

**Comment by B4nan** [comment]
Oh i see, you are using the nest request scopes instead of the RequestContext helper. I would rather suggest using the helper, that way will work for sure, and I am almost sure it will be better performance wise too (but measure if you want to be sure).

**Comment by B4nan** [comment]
Yeah its a bug for sure, lets keep this open, i havent had time to check the repro yet, worst case it might be a wontfix but want to check it first. Btw have you tried using the `@InjectRepository` decorator? Might produce different results.

**Comment by B4nan** [comment]
The problem here is that repositories depend on the EM from core, while your test case depends on the one from driver package, which is its extension. Nest DI does not understand the extension, so injects two different things. If you change the EM import in your test to use `core` package, it passes.

**Comment by B4nan** [comment]
Oh right, found the trick, I can register the EM extension provides as aliases myself, simply by stating they depend on the core EM and return that.
