### ISSUE TITLE
Cant not inject Entity Manager

### ISSUE THREAD

**Issue by samuraitruong** [mikro-orm/nestjs#68]
**Describe the bug**
My project is working before but suddently, it stop working because DI cant load EntityManager, While the InjectRepository still working in the same class

**Stack trace**
```
@Injectable()
export class MeterInfoService implements IMeterInfoService {
  constructor(
    @InjectRepository(Site)
    private readonly siteRepository: EntityRepository<Site>,
    @InjectRepository(Meter)
    private readonly meterRepository: EntityRepository<Meter>,
    @InjectRepository(Channel)
    private readonly channelRepository: EntityRepository<Channel>,
    private readonly em: EntityManager,
  ) {}

...
```
Got below error
```
ERROR [ExceptionHandler] Nest can't resolve dependencies of the MeterInfoService (SiteRepository, MeterRepository, ChannelRepository, ?). Please make sure that the argument SqlEntityManager at index [3] is available in the MeterInfoModule context.

Potential solutions:
- If SqlEntityManager is a provider, is it part of the current MeterInfoModule?
- If SqlEntityManager is exported from a separate @Module, is that module imported within MeterInfoModule?
  @Module({
    imports: [ /* the Module containing SqlEntityManager */ ]
  })

Error: Nest can't resolve dependencies of the MeterInfoService (SiteRepository, MeterRepository, ChannelRepository, ?). Please make sure that the argument SqlEntityManager at index [3] is available in the MeterInfoModule context.

Potential solutions:
- If SqlEntityManager is a provider, is it part of the current MeterInfoModule?
- If SqlEntityManager is exported from a separate @Module, is that module imported within MeterInfoModule?
  @Module({
    imports: [ /* the Module containing SqlEntityManager */ ]
  })
```
After dig deeper in the code, I found that there is another package using @mikro-orm/knex so that why it make  the injection look for SQLEntityManager

**To Reproduce**
1. setup monorepo with nestjs application is not the root workspace
2. enable yarn workspace v2 that make all the package going to top level node_modules (../../)
3. run yarn start:dev

**Expected behavior**
The EntityManager should able to inject

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | ? |
| your-driver | ? |

**Comment by rat-matheson** [comment]
Did you have any progress with this?  I'm having the same issue.  In my case, I'm trying to use the SqlEntityManager in a forFeature module.  I'm using sqlite.

**Comment by B4nan** [comment]
I will need a complete reproductions for this, but so far this sounds more like misconfigurations than bugs.

With that said, there is a problem with EM injection when the nest js requests scopes are used (#67).

**Comment by B4nan** [comment]
Lets reopen with a reproduction if #82 does not help. But the OP seems like you just used wrong package for import.
