### ISSUE TITLE
Request scoping when using microservices

### ISSUE THREAD

**Issue by jblyberg** [mikro-orm/nestjs#71]
Perhaps I'm missing something or the docs are a little unclear on this so this is more of a question. I have a number of microservices that I would like to migrate from mongoose to mikro-orm, but it seems like the middleware is specifically for express instances (with some caveats for fastify)

```js
  use(req: unknown, res: unknown, next: (...args: any[]) => void) {
    RequestContext.create(this.orm.em, next);
  }
```

So It seems the automatic middleware is out, so if I disable that and use ALS, I still need to have access to the request object:

```js
// register the request context middleware
const app = await NestFactory.create(AppModule, { ... });

const orm = app.get(MikroORM);
app.use((req, res, next) => {
  storage.run(orm.em.fork({ useContext: true }), next);
});
```

The microservice app context is incompatible with that obviously:

```ts
const app = await NestFactory.createMicroservice<MicroserviceOptions>(.....);
```

In this case, is it possible to hook in to each transport request to create a new context?

**Comment by B4nan** [comment]
Try this: 

https://mikro-orm.io/docs/identity-map#userequestcontext-decorator
