### ISSUE TITLE
forFeature method not accepting EntitySchema as valid type for entities argument

### ISSUE THREAD

**Issue by perebusquets** [mikro-orm/nestjs#79]
**Describe the bug**
First of all, awesome project, keep the great work! :)

I´m trying to use to use MikroORM in NestJS setup as a monorepo (so no glob file patterns for me), and trying to use the `autoLoadEntities` option to be able declare the entities in each module via `forFeature`. 
The problem is that I would like to use EntitySchema declaration instead of using decorators, and the type in the `forFeature` method doesn't allow them. 
I've checked that, if I ignore the typescript error, everything works fine, so my guess is that it's just an oversight of not also declaring EntitySchema as a valid type there.

**Stack trace**
```
Type 'EntitySchema<Account, undefined>' is not assignable to type 'EntityName<AnyEntity<any>>'.
```

**To Reproduce**
1. Instantiate MikroOrmModule with `autoLoadEntities` option enabled.
2. Declare in the `forFeature` method the EntitySchema you want to use.
3. Typescript explodes
4. Ignore TS error
5. Everything works as expected

**Expected behavior**
`forFeature` method to allow for EntitySchema type.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.15.1 |
| typescript | 4.7.4 |
| mikro-orm | 5.2.0 |
| mongodb-driver | 5.2.0 |

**Comment by B4nan** [comment]
That's weird. The `EntityName` type comes from the ORM and explicitly has the `EntitySchema` in union:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/typings.ts#L148

Aparently its caused by the generic type value.
