### ISSUE TITLE
Add support for `autoLoadEntities`

### ISSUE THREAD

**Issue by chasevida** [mikro-orm/nestjs#8]
**Describe the bug**
First off, great project - I'm really grateful for all the work you've put in on this.

The issue I'm running into with this module is when it's run within a [nest monorepo](https://docs.nestjs.com/cli/monorepo) the glob patterns for entity discovery does not work (for `js` or `ts` files). This appears to be a known issue also faced with TypeORM where they have added an [`autoLoadEntities`](https://docs.nestjs.com/techniques/database#auto-load-entities) prop in order to resolve it.

Not importing entities in manually results in a `No entities were discovered` error on startup.

I can (and am presently) importing files manually but this seems a bit unintuitive given that now I have to expose these from scoped libraries within the larger nest monorepo.

**To Reproduce**
1. Create a new nest project as a [monorepo](https://docs.nestjs.com/cli/monorepo)
2. Install and configure `@mikro-orm/nestjs` as a library module
3. Configure an entity or two and use the glob patter in the Mikro ORM config
4. Run the application

**Expected behavior**
All entities should be discovered based on their glob and load within Mikro ORM.

**Additional context**
I'd be happy to do this another way if I can scope a Mikro ORM instance per library module if that's better but I'm unsure if Mikro ORM sets itself up globally and wouldn't allow this.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.x |
| @nestjs/core | 7.0.0 |
| @mikro-orm/core | 4.0.3 |
| @mikro-orm/nestjs | 4.0.0 |

**Comment by B4nan** [comment]
I thought that nest monorepo mode = using webpack. And webpack = you cannot use folder based discovery at all.

**Comment by chasevida** [comment]
Yeah that's sounds right (first 48 hours into nest/mikro-orm). However, I wasn't sure how TypeORM was able to do this and wondered if I was missing something here. I might go through the docs again to see if there's a way I can register entities locally (in their seperate module scopes) before they are instantiated in root.

**Comment by B4nan** [comment]
Looking at the `autoLoadEntities`, sure we can do the same here, it's just not supported currently.
