### ISSUE TITLE
How to approach Migrations inside a NestJS MikroORM Project?

### ISSUE THREAD

**Issue by bharath6365** [mikro-orm/nestjs#91]
I'm using the MikroORM Nestjs Integration. I was wondering if the MikroORM Migration CLI can figure out the MikroORM configuration from MikroORM.forRoot() module configuration. 
https://docs.nestjs.com/recipes/mikroorm

The reason I'd like to see something like this is because we store all DB connection information inside a config that is exposed through a Nestjs Module.

If this is not possible, can you guide me about the possible alternatives? Thanking you in advance for your time.

**Comment by B4nan** [comment]
Nope, this is not possible, the `forRoot` call can be anywhere, and even if we knew where it is, I don't see how it could work.

Do it the other way around, define everything in ORM config and import/use that when calling `forRoot`. You can even omit the `forRoot` parameter, and the ORM config will be loaded automatically.
