### ISSUE TITLE
Yarn 3.3 in package.json

### ISSUE THREAD

**Issue by Eddort** [mikro-orm/nestjs#94]
Hey team! I noticed that you updated the engine conditions in package.json in the last update. Unfortunately, it affected my project and probably many others. I think it’s better to make such changes in a major release.

Do you think it would be possible to fix the situation with another minor release, returning to yarn 1.x support?
![telegram-cloud-photo-size-2-5260705755412152903-x](https://user-images.githubusercontent.com/32648340/208396129-ecd36d15-aa41-4df1-bb55-346c5ad1a869.jpg)

**Comment by B4nan** [comment]
this affects only collaborators, not users

**Comment by Eddort** [comment]
> this affects only collaborators, not users
Maybe I'm wrong, but I was able to repeat it on a new project:

![image](https://user-images.githubusercontent.com/32648340/208399577-43856307-a9d6-4700-9286-aff5c0ef4448.png)

**Comment by B4nan** [comment]
Cant help myself but this seems like a bug in yarn.

**Comment by B4nan** [comment]
FYI the engines constraint is removed in 5.1.4

**Comment by Eddort** [comment]
> FYI the engines constraint is removed in 5.1.4

Thank you!
