### ISSUE TITLE
v5.1.3 requires yarn 3, which removes classic yarn support

### ISSUE THREAD

**Issue by oznakn** [mikro-orm/nestjs#95]
**Describe the bug**

Before the release v5.1.3 there was no yarn version requirement, and the package was working fine with the classic yarn. However, after the upgrade this package now requires yarn 3.

On a side note, I am not really sure but I don't think that yarn v3 even exists.

**To Reproduce**
Try to install the package `@mikro-orm/nestjs` with classic yarn (yarn v1).

**Expected behavior**
I believe there is no need for requirement for yarn v3 (or v2) since the package was working fine with classic yarn.

**Versions**

| Dependency | Version |
| - | - |
| node | 16 |
| typescript | 4.8 |
| mikro-orm | 5.5 |

**Comment by B4nan** [comment]
the engines constraint is apparently weird, this sounds more like yarn v1 bug to me, but lets remove it. 

note that yarn v1 is a legacy project, yarn stable is v3, the project is in yarn/berry repository. the constrain should be taken into account only for the project collaborators, not for users - in other words, this was never meant to surface when you install it as a dependency...

**Comment by B4nan** [comment]
fixed in 5.1.4

**Comment by oznakn** [comment]
Thank you!
